#!/usr/bin/env python
import pcf8591 as ADC
import RPi.GPIO as GPIO
import time
import datetime
import math
import csv
import daddysemail
DO = 27
#    GPIO.cleanup()
GPIO.setmode(GPIO.BCM)
GPIO.setup(DO, GPIO.OUT)
    

def main():
    timer = 0
    f = open("soil humidity.csv","a")
    c = csv.writer(f)
    while True:
        GPIO.output(DO, False)
        ADC.setup(0x48)
        print("ADC on, warming up")
        time.sleep(5)
        analogVal = ADC.read(0)
        GPIO.output(DO,True)
        print("ADC off")
        Vr = 5 * float(analogVal) / 255
        Rt = 10000 * Vr / (5 - Vr)
        temp = 1/(((math.log(Rt / 10000)) / 3950) + (1 / (273.15+25)))
        analog_temp = temp - 273.15
        print(datetime.datetime.now(),analog_temp)
        c.writerow([datetime.datetime.now(),analog_temp])
        if timer == 6:
            f.close()
            daddysemail.all()
            timer = 0
            f = open("soil humidity.csv","a")
            c = csv.writer(f)
        time.sleep(5)
        timer = timer + 1
        
def destroy():
    f.close()
    GPIO.output(DO,True) 
    GPIO.cleanup()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        destroy()
#!/usr/bin/env python
import pcf8591 as ADC
import RPi.GPIO as GPIO
import time
import datetime
import math
import csv
import daddysemail
DO = 27
#    GPIO.cleanup()
GPIO.setmode(GPIO.BCM)
GPIO.setup(DO, GPIO.OUT)
    

def main():
    timer = 0
    f = open("soil humidity.csv","a")
    c = csv.writer(f)
    while True:
        GPIO.output(DO, False)
        ADC.setup(0x48)
        print("ADC on, warming up")
        time.sleep(5)
        analogVal = ADC.read(0)
        GPIO.output(DO,True)
        print("ADC off")
        Vr = 5 * float(analogVal) / 255
        Rt = 10000 * Vr / (5 - Vr)
        temp = 1/(((math.log(Rt / 10000)) / 3950) + (1 / (273.15+25)))
        analog_temp = temp - 273.15
        print(datetime.datetime.now(),analog_temp)
        c.writerow([datetime.datetime.now(),analog_temp])
        if timer == 6:
            f.close()
            daddysemail.all()
            timer = 0
            f = open("soil humidity.csv","a")
            c = csv.writer(f)
        time.sleep(5)
        timer = timer + 1
        
def destroy():
    f.close()
    GPIO.output(DO,True) 
    GPIO.cleanup()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        destroy()
